### ISSUE TITLE
No Time Entries model

### ISSUE THREAD

**Issue by RobertLowe** [freshbooks/freshbooks-nodejs-sdk#19]
@bhaskarmurthy @alexkung1

This isn't published and the deadline to migrate is rushing close. Giving devs little time to migrate unless they use their own implementations.

Additionally, there is no model included for Time Entries. And time entries no longer belong to a task.

---

Context: I automate my time entries. This will make generating invoices difficult. 

Old API: https://www.freshbooks.com/classic-api/docs/time-entries#time_entry.create

New API: https://www.freshbooks.com/api/time_entries

Wtf? 🤷‍♂️

**Comment by anotheri** [comment]
Still not published (yarn)

**Comment by amcintosh** [comment]
Hey!
Sorry about the delay, they are published now: https://www.npmjs.com/org/freshbooks

We'll look into getting the time entries added, but I'm sorry I don't have an ETA.

**Comment by amcintosh** [comment]
@RobertLowe Hi. We just released a new version to npm that supports the time entries endpoint. We'll be working on support for projects, services, and tasks next. 

Sorry for the delay, but we've really only just taken over on this project.
