### ISSUE TITLE
When fetching vendors the `vendorId` is not retuned

### ISSUE THREAD

**Issue by michael-polonsky** [freshbooks/freshbooks-nodejs-sdk#396]
In function `transformBillVendorsData` you assume that API endpoint returns `vendorId` and in reallity it returns `vendorid` (lowercase `i`)

Thus the vendorId is always set to `undefined`

**Comment by michael-polonsky** [comment]
in `BillVendors.ts`

`vendor_id: vendorId,` -> `vendorid: vendorId`

**Comment by amcintosh** [comment]
Hi @michael-polonsky. This should be resolved now and a new version has been published.
