### ISSUE TITLE
API Returning Empty Array of data

### ISSUE THREAD

**Issue by wesbos** [freshbooks/freshbooks-nodejs-sdk#547]
Hello - not sure if this is the right spot to report this as it happens with and without the Node.js API, but I figure I'd do it.

The API is authenticating me just fine. I have created an app with expenses:read and expenses:write scopes and created an auth token for my own log in.

When I call the `/me` endpoint, I get the account ID and then create a request like this:

```js
const data = await fetch(`https://api.freshbooks.com/accounting/account/${ACCOUNT_ID}/expenses/expenses`, {
  headers,
  method: 'GET',
}).then((res) => res.json());
console.dir(data, { depth: null });
```

That gives me this as a response:

```
{
  response: {
    result: { expenses: [], page: 1, pages: 323, per_page: 15, total: 4834 }
  }
}
```

Which is the correct counts of everything reflected in my freshbooks account, but the expense array is empty.

Same with the expense category endpoint - I get the correct counts, but no data.

```js
{
  response: {
    result: { categories: [], page: 1, pages: 6, per_page: 15, total: 88 }
  }
}
```

I've tried to pass arguments like `?page=1`. The counts update, but no data.

Exact same response with the Node.js SDK.

```js
const expenseResponse = await client.expenses.list(ACCOUNT_ID);
console.log(expenseResponse.data.expenses); // []
```

Am I doing anything wrong? Is the API broken / supported? I noticed lots of broken code samples and images on the docs page.

**Comment by amcintosh** [comment]
Hi @wesbos! Since it looks like you're encountering this issue whether you use the sdk or calling the API directly, I suggest you reach out to api@freshbooks.com and they should be able to assist you.

**Comment by wesbos** [comment]
Ok thank you - I've submitted this to the URL. Will close this
