### ISSUE TITLE
TypeScript type definition for Project is broken

### ISSUE THREAD

**Issue by iBelieve** [freshbooks/freshbooks-nodejs-sdk#56]
- IDs (`id`, `clientId`, `services.id`, `services.businessId`, and probably others) are listed as strings but are actually numbers
- All the properties are listed as optional, but that doesn't seem right (except maybe for the POST/PUT endpoints, in which case there's ways to use TypeScript to wrap a type and make all properties optional), especially since nullable properties are specifically marked as such.
- Enums (ProjectType/BillingMethod/BilledStatus) all compile down to numbers but are actually strings.

The enums should probably be something like:

```js
export enum FreshBooksProjectType {
  FixedPrice = 'fixed_price',
  HourlyRate = 'hourly_rate',
}

export enum FreshBooksBillingMethod {
  BusinessRate = 'business_rate',
  ProjectRate = 'project_rate',
  ServiceRate = 'service_rate',
  TeamMemberRate = 'team_member_rate',
}

export enum FreshBooksBilledStatus {
  Billed = 'billed',
  PartiallyBilled = 'partially_billed',
  Unbilled = 'unbilled',
}
```

**Comment by amcintosh** [comment]
Hi! Thanks for the feedback. We'll look into it.
