### ISSUE TITLE
Incompatible error response received from API. 

### ISSUE THREAD

**Issue by sergioshev** [freshbooks/freshbooks-nodejs-sdk#573]
Seems like API is sending an unexpected error response structure.
I'm unable to get well formed error object while creating an invoice, however i'm receiving

```
TypeError: Cannot read properties of undefined (reading 'errors')
     at isAccountingErrorResponse (/usr/src/backend/node_modules/@freshbooks/api/src/models/Error.ts:32:33)
     at Object.transformInvoiceResponse [as transformResponse] (/usr/src/backend/node_modules/@freshbooks/api/src/models/Invoices.ts:145:3)
     at transform (/usr/src/backend/node_modules/axios/lib/core/transformData.js:22:15)
     at Object.forEach (/usr/src/backend/node_modules/axios/lib/utils.js:251:10)
     at Object.transformData (/usr/src/backend/node_modules/axios/lib/core/transformData.js:21:9)
     at onAdapterRejection (/usr/src/backend/node_modules/axios/lib/core/dispatchRequest.js:70:46)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

After a digging for a while, the response interceptor used by axios is handling an unexpected error structure
`const isAccountingErrorResponse = ({ error, error_type: errorType, response }) => error || errorType || response.errors;`

but the response has this shape

```
{
  "code": 3,
  "message": "Request failed with status_code: 422",
  "details": [{
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "reason": "8003",
    "domain": "accounting.api.freshbooks.com",
    "metadata": {
      "object": "invoice",
      "message": "This invoice number is already in use. Please choose another.",
      "value": "XXXXX-0001",
      "field": "invoice_number"
    }
  }]
}
```

there is no such attribute _response.errors_

I suspect there were an api update, but the sdk wasn't upgraded.

**Comment by amcintosh** [comment]
Hi @sergioshev. Thanks for reaching out. You are correct, the error format recently changed for some endpoints. We're in the process of updating and should have a fix soon (you can see similar work in the [Python SDK](https://github.com/freshbooks/freshbooks-python-sdk/issues/49)).

**Comment by sergioshev** [comment]
FYI: also there is another issue if you send create invoice request with lines containing amounts as numbers, not strings (sdk types require to be numbers). 
i receive something like this

```
invoice_wrapper.invoice.lines[0].unit_cost.amount: invalid value <SOME amount> for type TYPE_STRING
```

after converting it to string and ignoring typescript type error, it works.

**Comment by amcintosh** [comment]
@sergioshev Yes, the API used to be very permissive for monetary amounts, accepting either a number or a string and then coercing and returning only a string. The most recent API version is less permissive. I'll put a fix up for the SDK. 

Thanks for finding this.
